### ISSUE TITLE
Capstone Defense Checklist ✔️

### ISSUE THREAD

**Issue by taylorcate** [taylorcate/NuttingVariorum#31]
- [x] Cut together an MS Transcription Process Video to screen at the beginning of the defense. 
- [x] Finish outlining the Variorum Plot Graph for the section you will present. 
- [x] Finish wireframing the website. 
- [x] Map out one section of the flipbook that includes all interactive components.  
- [x] Assemble presentation materials - PowerPoint, Prezi, etc. 
- [ ] Begin writing new documentation for this stage of the project. 
- [ ] Record yourself reading the section you plan to present on.

**Comment by taylorcate** [comment]
![Variorum Plot Graph - Publication](https://user-images.githubusercontent.com/35510197/56235869-ee673400-604d-11e9-905d-900e7e0c57da.png)

**Comment by taylorcate** [comment]
## [Link to Defense Slides](https://docs.google.com/presentation/d/1oTJu7nQHIJTFW1qAOrUHFsUxxnaVZgwpHDR8Uhxtu4E/edit?usp=sharing)
